---
# This task will install Kitab and update to git

#- name: Install Kitab and update to git
#  git: repo=https://github.com/tareko/Kitab-Al-Shifa.git
#       dest=/vagrant/kitab
#       accept_hostkey=yes

- name: Install Kitab dependencies
  action: apt pkg={{ item }} state=present
  with_items:
   - wkhtmltopdf

- name: Copy configuration files
  copy: src=core.php dest=/vagrant/kitab/app/Config/core.php owner=www-data group=www-data mode=0600 force=no
- copy: src=database.php dest=/vagrant/kitab/app/Config/database.php owner=www-data group=www-data mode=0600 force=no
- copy: src=email.php dest=/vagrant/kitab/app/Config/email.php owner=www-data group=www-data mode=0600 force=no
 
- name: Create database for Kitab
  mysql_db: name=kitab state=present
- mysql_db: name=kitab state=import target=/vagrant/kitab/app/Config/Schema/kitab.sql
 
- name: Create database for Drupal
  mysql_db: name=drupal state=present
- mysql_db: name=drupal state=import target=/vagrant/kitab/app/Config/Schema/drupal.sql

- name: Create database for testing
  mysql_db: name=test state=present
  
- name: Create user for Kitab
  mysql_user: name=kitab password=kitab priv=kitab.*:ALL/drupal.*:ALL/test.*:ALL state=present
